[project]
dependencies = [
  "colorama",
  "pywin32 ; platform_system == \"Windows\"",
]
name = "rpycli"
version = "0.0.3"

[project.optional-dependencies]
dev = [
  "mypy",
  "pyright",
  "pytest",
]

[tool.mypy]
packages = [
  "rpycli",
]
strict = true
warn_unused_ignores = false
